### ISSUE TITLE
question: does this host the tz data in the project or is it hosted outside, looks like npm hosted static file?

### ISSUE THREAD

**Issue by jschlesser** [kevmo314/browser-geo-tz#3]
Does this have all the data in it or is it dependent on an outside resource?
https://github.com/kevmo314/browser-geo-tz/blob/d21ca482e75fb3150dea1b7ca8ce794aafe2819f/src/find.ts#L10C6-L10C84

Im not complaining, just wondering.  It looks like it's getting the geo data (a protobuf file?) hosted on npm?  What would I do if I wanted to host that myself?  Should I download the file and change the source?   Do you have a reference for how to produce the file?

**Comment by kevmo314** [comment]
It references the `node-geo-tz` file hosted on a CDN. If you'd like to host that yourself we probably can update the library to accept a path that can be configured, that seems pretty reasonable and would also address the versioning issue #1

With regards to producing the file, run `npm run build` in this repo: https://github.com/evansiroky/node-geo-tz
